App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    table: npd_user
    id:
        id:
            column: uuid
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        email:
            type: string
            length: 180
            unique: true
        roles:
            type: json
        password:
            type: string
        firstName:
            type: string
        lastName:
            type: string
        passwordNeedToBeChanged:
            type: boolean
            nullable: true
        passwordResetToken:
            type: string
            nullable: true
        created:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        lastLoginDate:
            type: datetime
            nullable: true
    manyToMany:
        courses:
            targetEntity: App\Entity\Course
            joinTable:
                name: npd_user_course
                joinColumns:
                    user_id:
                        referencedColumnName: uuid
                inverseJoinColumns:
                    course_id:
                        referencedColumnName: id
            cascade:
                - all

        notifications:
            targetEntity: App\Entity\Notification
            joinTable:
                name: npd_user_read_notifications
                joinColumns:
                    user_id:
                        referencedColumnName: uuid
                        onDelete: CASCADE
                inverseJoinColumns:
                    notification_id:
                        referencedColumnName: uuid
                        onDelete: CASCADE
            cascade:
                - all
